### PR TITLE
Leadership amber

### PR DESCRIPTION
**Pull request by amacbain1**
Component: leadership #23-this component still needs the drag component (Luis is working on). Until then horizontal scrollbars are still visible on most browsers.

### CODE REVIEW

**Comment by lloan** [comment]
@amacbain1 Awesome job here. We are just missing the dragging but will merge this and have @VelazquezLuis add dragging with his component. Or is that in progress already?

**Comment by amacbain1** [comment]
Working on adding the drag component.  I will need to check with Luis as I am having issues with the component loading and Swiper.

**Comment by lloan** [comment]
@amacbain1 it looks like you might be missing the `swiper` package. I'm currently testing the #20 component and it looks like adding that fixes a couple of issues.

**Comment by amacbain1** [comment]
Yes, added swiper- it’s on my local. Have not pushed up the changes yet.The drag works great but  I have to refresh the page twice before UL will show.  On first loading only first list item appears.

**Comment by lloan** [comment]
Interesting. If you get a chance, upload changed and I can test it too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
