### PR TITLE
Created Success Stories component

### PR DESCRIPTION
**Pull request by tonynguyen111997**
This PR references issue #19 

Created Success Stories component.

The JavaScript file with the user's information is called successStoriesData.js. I wasn't sure where to put this file, so for now I placed it inside util. 

This PR also updates the .eslintrc.json to include the rule `react/jsx-uses-vars`. This rule finds variables used in JSX and marks them as used.

image

### CODE REVIEW

**Comment by johnathantng** [comment]
Just took a look at your code. From what I can see, everything looks good so far! Hopefully we can have another pair of eyes review it just to be sure. Keep up the great work!

**Comment by tonynguyen111997** [comment]
@lloan Great catch! I didn't realize they weren't lined up. So I have the social media icons only appear if the user provides a twitter\facebook or both. If you refresh the page a couple times it will load Erik's story, which does have social media icons.

**Comment by tonynguyen111997** [comment]
Fixed issue of name & job title not lining up

image

**Comment by lloan** [comment]
Approved - will merge once we get one full story from a member. 

@Luna-Coder - is it possible to have you provide us all the appropriate information for your story? Thanks!

**Comment by tonynguyen111997** [comment]
This component now has one story.

image

**Pull request merged**
