### PR TITLE
add floating right and left bars

### PR DESCRIPTION
**Pull request by yzhan407**
create floating bar

when the floating bar goes beyond the white page, it is invincible. there could be a small modification in the future.

### CODE REVIEW

**Comment by lloan** [comment]
Overall its almost there. I noticed this when expanding the window or going over 1400px:

image

Also, minor enhancement that would be awesome, which I know the design might not have taken in to account - would it be possible to try and have 40-48px of clickable space for the icons? The minimum that links/icons should have of clickable space is around that size for people using touch devices (mobile).

**Comment by yzhan407** [comment]
Hi,
  I have made a new pull request about the changes you mentioned. The area that is clickable is now 40px and the position of the floating bar is reasonable even if the window is over 1440px.

if there are more problems I will be happy to change, just let me know.
Thanks

**Comment by lloan** [comment]
reviewing changes for merge

**Comment by lloan** [comment]
merge conflicts resolved

**Comment by lloan** [comment]
@tonynguyen111997 @johnathantng let's take a look at this see if it's alright as far as user experience goes - test it out:

image

image

image

image

**Comment by lloan** [comment]
Updated size and color - size to match other icons and color to be match the feel of other side. 

image

**Pull request merged**
